from os import path

def replacement(chars):
    inside = ', '.join(["'\\u{%s}'" % c for c in chars.split(' ')])
    return '(%s,)' % inside


txt = open('./scripts/CaseFolding.txt')
rs = open(path.abspath('./src/unicode/map.rs'), 'w')

rs.write('// Generated by scripts/mapgen.py\n\n')
rs.write('use super::fold::Fold;\n\n')
rs.write("pub fn lookup(orig: char) -> Fold {\n")
rs.write('    match orig as u32 {\n')
for line in txt.readlines():
    if line[0] is not '#':
        parts = line.split('; ')
        if len(parts) > 2 and parts[1] in 'CF':
            #if ' ' in parts[2]:
            #    rs.write('//')
            rs.write("        0x%s => %s.into(),\n" % (parts[0], replacement(parts[2])))
rs.write('        _ => (orig,).into()\n')
rs.write('    }\n')
rs.write('}\n')


